//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Equipo()
        {
            this.TBL_Jugador = new HashSet<TBL_Jugador>();
            this.TBL_Juego = new HashSet<TBL_Juego>();
            this.TBL_Juego1 = new HashSet<TBL_Juego>();
        }
    
        public int IdEquipo { get; set; }
        public string NombreEquipo { get; set; }
        public Nullable<System.DateTime> FechaFundacion { get; set; }
        public Nullable<int> IdLiga { get; set; }
    
        public virtual TBL_Liga TBL_Liga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Jugador> TBL_Jugador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Juego> TBL_Juego { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Juego> TBL_Juego1 { get; set; }
    }
}
