//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Juego
    {
        public int IdJuego { get; set; }
        public int IdLiga { get; set; }
        public int IdEquipoLocal { get; set; }
        public int IdEquipoVisita { get; set; }
        public int GolesLocal { get; set; }
        public int GolesVisita { get; set; }
    
        public virtual TBL_Equipo TBL_Equipo { get; set; }
        public virtual TBL_Equipo TBL_Equipo1 { get; set; }
        public virtual TBL_Liga TBL_Liga { get; set; }
    }
}
