//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Liga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Liga()
        {
            this.TBL_Equipo = new HashSet<TBL_Equipo>();
            this.TBL_Juego = new HashSet<TBL_Juego>();
        }
    
        public int IdLiga { get; set; }
        public string NombreLiga { get; set; }
        public Nullable<int> IdNivelLiga { get; set; }
        public Nullable<long> PremioLiga { get; set; }
        public string DescripcionLiga { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Equipo> TBL_Equipo { get; set; }
        public virtual TBL_NivelLiga TBL_NivelLiga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Juego> TBL_Juego { get; set; }
    }
}
